name: 'CARS_FUEL'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'CARS_FUEL'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  CARS_FUEL:                    # Must match the project name above
    # Applies to all files under models/staging/
    staging:
      +materialized: view
    # Applies to all files under models/marts/
    marts:
      +materialized: table

# Project-level variables
vars:
  project_id: 'samidm'