name: 'CARS_FUEL'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  CARS_FUEL:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table